#!/bin/bash

# make bash behave
set -euxo pipefail
IFS=$'\n\t'

codename=stretch
pg_majors=( "${@}" )

# explicitly set user/group IDs
groupadd -r circleci --gid=1729
useradd -mg circleci --uid=1729 --shell=/bin/bash circleci

# import key and keep apt-key from issuing warnings
curl -sf https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -

mv /tmp/docker-dpkg.cfg /etc/dpkg/dpkg.cfg.d/docker

echo "Writing /etc/apt/sources.list.d/pgdg.list..." >&2

# TODO: in a future Debian release, backports will become unnecessary (we need clang-6.0)
cat > /etc/apt/sources.list.d/pgdg.list <<EOF
deb     http://deb.debian.org/debian ${codename}-backports                main
deb-src http://apt.postgresql.org/pub/repos/apt/ ${codename}-pgdg         main
deb-src http://apt.postgresql.org/pub/repos/apt/ ${codename}-pgdg-testing 12
EOF

echo "Running apt-get update..." >&2
apt-get update

echo "Installing tools for building Debian packages..." >&2
apt-get install -y --no-install-recommends \
  devscripts \
  fakeroot \
  lintian

pg_pkgs=( "${pg_majors[@]/#/postgresql-}" )
apt-get build-dep -y "${pg_pkgs[@]}"
