#!/bin/bash

# make bash behave
set -euxo pipefail
IFS=$'\n\t'

codename=stretch
pg_majors=( "${@}" )
citus_pkg_rev=1

mkdir -p $HOME/workspace && cd $HOME/workspace

git clone https://github.com/citusdata/citus.git
rm -rf citus/.git

build_ext() {
  pg_major="$1"

  cd $HOME/workspace

  build_dir="build-${pg_major}"
  echo "Beginning build of citus for PostgreSQL ${pg_major}..." >&2

  # do everything in a subdirectory to avoid clutter in current directory
  mkdir "${build_dir}" && cd "${build_dir}"
  
  ../citus/configure PG_CONFIG="/usr/lib/postgresql/${pg_major}/bin/pg_config"
  make -j7 && mkdir install && make DESTDIR="$(pwd)/install" install

  cd install && find . -type f -print > ../files.lst
  tar cvf $HOME/workspace/install-${pg_major}.tar `cat ../files.lst`

  cd .. && rm -rf install files.lst && make clean
}

for pg_major in "${pg_majors[@]}"
do
  build_ext "${pg_major}"
done
