#!/bin/bash

# make bash behave
set -euxo pipefail
IFS=$'\n\t'

codename=stretch
pg_version=11

# explicitly set user/group IDs
groupadd -r builder --gid=999
useradd -mg builder --uid=999 --shell=/bin/bash builder

# import key and keep apt-key from issuing warnings
curl -sf https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -

mv /tmp/docker-dpkg.cfg /etc/dpkg/dpkg.cfg.d/docker

apt-get update && apt-get install -y --no-install-recommends apt-transport-https debian-archive-keyring

echo "Writing /etc/apt/sources.list.d/pgdg.list..." >&2

cat > /etc/apt/sources.list.d/pgdg.list <<EOF
deb http://apt.postgresql.org/pub/repos/apt/ ${codename}-pgdg main ${pg_version}
EOF

pkg_cloud_token='04c79f17bf82c6ee482ca210687bf542ecbd9dcbc0de671c'
pkg_cloud_url="https://${pkg_cloud_token}:@packagecloud.io/install/repositories/citusdata/circlecipoc/script.deb.sh"

curl -sf "${pkg_cloud_url}" | unique_id=extbuilder bash

cat > /etc/apt/preferences.d/citusdata_circlecipoc.pref <<EOF
Package: postgresql-server-dev-*
Pin: release o=packagecloud.io/citusdata/circlecipoc
Pin-Priority: 600
EOF
