name: save_logs_and_results
inputs:
  folder:
    required: false
    default: "log"
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: ${{ inputs.folder }}
      if-no-files-found: ignore
      path: |
        src/test/**/proxy.output
        src/test/**/results/
        src/test/**/tmp_check/master/log
        src/test/**/tmp_check/worker.57638/log
        src/test/**/tmp_check/worker.57637/log
