name: save_logs_and_results
inputs:
  folder:
    required: false
    default: "log"
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: ${{ inputs.folder }}
      if-no-files-found: ignore
      path: |
        ${GITHUB_WORKSPACE}/**/proxy.output
        ${GITHUB_WORKSPACE}/**/results/
        ${GITHUB_WORKSPACE}/**/tmp_check/master/log
        ${GITHUB_WORKSPACE}/**/tmp_check/worker.57638/log
        ${GITHUB_WORKSPACE}/**/tmp_check/worker.57637/log
