name: save_logs_and_results
inputs:
  folder:
    required: false
    default: "log"
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: ${{ inputs.folder }}
      if-no-files-found: ignore
      path: |
        **/proxy.output
        **/results/
        **/tmp_check/master/log
        **/tmp_check/worker.57638/log
        **/tmp_check/worker.57637/log
