name: save_logs_and_results
inputs:
  folder:
    required: false
    default: "log"
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: ${{ inputs.folder }}
      if-no-files-found: ignore
      path: |
        src/test/regress/proxy.output
        src/test/regress/results/
        src/test/regress/tmp_check/master/log
        src/test/regress/tmp_check/worker.57638/log
        src/test/regress/tmp_check/worker.57637/log
