name: save_regressions
inputs:
  folder:
    required: false
    default: ""
runs:
  using: composite
  steps:
  - name: Regressions
    run: |-
      if [ -f "src/test/regress/regression.diffs" ]; then
        cat src/test/regress/regression.diffs
        exit 1
      fi
    if: failure()
    shell: bash
  - uses: actions/upload-artifact@v3.1.1
    if: ${{ inputs.folder == '' }}
    with:
      name: regression.diffs
      path: src/test/regress/regression.diffs
  - uses: actions/upload-artifact@v3.1.1
    if: ${{ inputs.folder != '' }}
    with:
      path: src/test/regress/regression.diffs
      name: ${{ inputs.folder }}/regression.diffs
