name: save_regressions
inputs:
  folder:
    required: false
    default: "log"
runs:
  using: composite
  steps:
  - name: Regressions
    run: |-
      if [ -f "src/test/regress/regression.diffs" ]; then
        echo "### ${{ inputs.folder }}" >> $GITHUB_STEP_SUMMARY
        cat src/test/regress/regression.diffs >> $GITHUB_STEP_SUMMARY
      fi
    shell: bash
  - uses: actions/upload-artifact@v3.1.1
    with:
      path: ${GITHUB_WORKSPACE}/**/regression.diffs
      name: ${{ inputs.folder }}
      if-no-files-found: ignore

