
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);
SELECT run_command_on_workers($$SELECT sum(numbackends) FROM pg_stat_database;$$);
select pg_sleep(0.05);



