CREATE SCHEMA "generated_identities";
SET search_path TO "generated_identities";

DROP TABLE IF EXISTS test;

CREATE TABLE test (
    a int GENERATED BY DEFAULT AS IDENTITY,
    b bigint GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10),
    c smallint GENERATED BY DEFAULT AS IDENTITY,
    d serial,
    e bigserial,
    f smallserial,
    g int
);

select create_distributed_table('test', 'a');

\d generated_identities.test

\c - - - :worker_1_port

\ds+

\d generated_identities.test

\c - - - :master_port
SET search_path TO "generated_identities";

insert into test (g) values (1);

insert into test (g) select 2;

INSERT INTO test (g)
SELECT s FROM generate_series(3,7) s;

SELECT * FROM test ORDER BY 1;

select undistribute_table('test');

SELECT * FROM test ORDER BY 1;

\d generated_identities.test

INSERT INTO test (g)
SELECT s FROM generate_series(8,10) s;

SELECT * FROM test ORDER BY 1;

ALTER TABLE test
ADD COLUMN h INT GENERATED BY DEFAULT AS IDENTITY;

SELECT * FROM test ORDER BY 1;

select create_distributed_table('test', 'a');

select alter_distributed_table('test', 'g');

DROP SCHEMA "generated_identities" CASCADE;
