\set lineitem_1_data_file :abs_srcdir '/data/lineitem_1_data_file'
\set lineitem_2_data_file :abs_srcdir '/data/lineitem_2_data_file'
\set orders_1_data_file :abs_srcdir '/data/orders_1_data_file'
\set orders_2_data_file :abs_srcdir '/data/orders_2_data_file'
COPY lineitem_hash_part FROM :'lineitem_1_data_file' with delimiter '|'
COPY lineitem_hash_part FROM :'lineitem_2_data_file' with delimiter '|'
COPY orders_hash_part FROM :'orders_1_data_file' with delimiter '|'
COPY orders_hash_part FROM :'orders_2_data_file' with delimiter '|'
