name: Build & Test Citus with PG Master

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-and-test-pg-master:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libreadline-dev \
            zlib1g-dev \
            flex \
            bison \
            libxml2-dev \
            libxslt-dev \
            libssl-dev \
            git

      - name: Clone PostgreSQL Repository
        run: |
          # Clone PostgreSQL master branch
          git clone https://github.com/postgres/postgres.git
          cd postgres
          git checkout master

      - name: Build PostgreSQL from Source
        run: |
          cd postgres
          ./configure --prefix=/usr/local/pgmaster
          make -j$(nproc)
          sudo make install

      - name: Set PG Binaries Path
        run: echo "/usr/local/pgmaster/bin" >> $GITHUB_PATH

      - name: Verify PostgreSQL Build
        run: |
          pg_config --version

      - name: Build Citus
        run: |
          # Ensure the newly built PostgreSQL is used
          which pg_config
          ./ci/build-citus.sh

      - name: Run Citus Tests
        run: |
          # Example test – adjust the make target and test directory as needed
          make -C src/test/regress check-vanilla
